config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#homepage'
  resource :calendar, :covid
  get '/covid/:country', to: 'covids#country'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def homepage
    @countries = [['brazil', 'o Brasil'], ['us', 'os Estados Unidos'], ['united kingdom', 'o Reino Unido'],
                  ['canada', 'o Canada'], ['china', 'a China'], ['spain', 'a Espanha'], ['russia', 'a Russia'],
                  ['india', 'a Índia']]
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def show; end
end

app/controllers/covids_controller.rb
class CovidsController < ApplicationController
  def show; end
  def country
    @country = params[:country]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/covids_helper.rb
module CovidsHelper
end

app/views/application/homepage.html.erb
<h1>Homepage</h1>

<%= link_to 'Feriados Canadênses', calendar_path %> <br>
<%= link_to "Top 5 países com covid", covid_path %> <br>
<%= javascript_include_tag 'chart' %>
<% @countries.each do |country| %>
  <%= link_to 'Dados d' << country[1], '/covid/' << country[0] %><br>
<% end %>

app/views/calendars/show.html.erb
<%= javascript_include_tag "calendar" %>
<div id="event_calendar"></div>

<%= link_to 'Voltar', root_path %>

app/views/covids/country.html.erb
<%= javascript_include_tag 'chart' %>
<canvas id="countryChart"></canvas>
<h1 id="error"></h1>

<script>
    $(document).on('turbolinks:load', async function () {
        let ctx = document.getElementById('countryChart').getContext('2d');
        let covid_data = await get_country_data("<%= @country %>");
        console.log(covid_data);
        covid_data = covid_data.data
        let countryChart = new Chart(ctx, {
            type: 'pie',
            data: {
                labels: ['casos', 'mortes', "pessoas curadas"],
                datasets: [{
                    label: covid_data.country,
                    data: fetch_country_data(covid_data),
                    backgroundColor: ["rgba(0, 0, 0, 0.5)", "rgba(255, 0, 0, 0.5)", "rgba(0, 255, 0, 0.5)"]
                }]
            }
        })
    })
</script>

app/views/covids/show.html.erb
<%= javascript_include_tag 'chart' %>
<canvas id="myChart"></canvas>
<%= link_to 'Voltar', root_path %>

<script>
    $(document).on('turbolinks:load', async function () {
        let ctx = document.getElementById('myChart').getContext('2d');
        let covid_data = await get_data();
        console.log(covid_data);
        covid_data = covid_data.data
        covid_data = sort_contries_by_cases(covid_data)
        console.log(covid_data)
        covid_data = covid_data.slice(0, 5)
        let myChart = new Chart(ctx, {
            type: 'horizontalBar',
            data: {
                labels: fetch_label(covid_data),
                datasets: [{
                    label: 'Número de casos de covid',
                    data: fetch_cases(covid_data),
                    backgroundColor: "rgba (255, 255, 255, 0.5)"
                },
                    {
                        label: "Número de mortes",
                        data: fetch_deaths(covid_data),
                        backgroundColor: "red"
                    },
                    {
                        label: "Número de pessoas curadas",
                        data: fetch_recovered(covid_data),
                        backgroundColor: "green"
                    }]
            },
            options: {
                scales: {
                    xAxes: [{
                        stacked: true
                    }],
                    yAxes: [{
                        stacked: true
                    }]
                }
            }

        });
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

  </body>
</html>